version: 0.0
os: linux
files:
  - source: /
    destination: /home/cicd-test
hooks:
  ApplicationStart:
    - location: /scripts/deploy.sh
      timeout: 300
      runas: root
      cwd: /home/cicd-test